# Generated by Django 3.0.4 on 2020-12-11 20:48

from django.db import migrations, models
import reach.models


class Migration(migrations.Migration):

    dependencies = [
        ('reach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ImageUrl',
            field=models.FileField(null=True, upload_to=reach.models.upload_path),
        ),
    ]
